// <auto-generated />
namespace Blog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _1111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1111));
        
        string IMigrationMetadata.Id
        {
            get { return "201406101537526_1111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
